

# 8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [5]:
numbers = np.array([10,20,30,40,50])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

In [8]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [10]:
numbers = np.array([10,20,30,40,50])
print(numbers.size)
print(numbers.itemsize)

5
8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [16]:
arr1 = np.zeros(12)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arr1[5] = 1
arr1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [20]:
arr2 = np.arange(20,60)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [23]:
arr3 = np.arange(10)
arr3[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [26]:
arr4 = np.arange(12,21).reshape(3,3)
arr4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [27]:
arr5 = np.array([3,7,0,0,9,0])
np.nonzero(arr5)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [29]:
arr6 = np.random.rand(2,2,2)
arr6

array([[[0.56032492, 0.8217099 ],
        [0.9442577 , 0.61112655]],

       [[0.50383904, 0.28391831],
        [0.61259442, 0.40948014]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [31]:
arr7 = np.random.rand(9,9)
print("max ",np.max(arr7))
print("min",np.min(arr7))

max  0.9938304270614438
min 0.02207597807436279


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [32]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1


False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones


In [38]:
arr8 = np.ones(shape=(6,3))
arr9 = np.ones(shape=(3,4))
print("arr8 ", arr8)
print("___________________________")
print("arr9 ", arr9)

arr8  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
___________________________
arr9  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
print(np.dot(arr8,arr9))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
sum(range(5), -1)


np.int64(10)

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [41]:
from numpy import *
sum(range(5), -1)


np.int64(10)

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [42]:
# nan
# 0
# array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [44]:
a = np.array([1,3,4,5,6.8])
b = np.array([3,5,6,4])
print(np.intersect1d(a,b))

[3. 4. 5.]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [50]:
import numpy as np

a = np.random.random(10) * 10  # 0 dan 10 gacha 10 ta son
print("Asl massiv:\n", a)


b1 = np.floor(a)

b2 = np.trunc(a)

b3 = a.astype(int)

b4 = np.fix(a)

print("\n1-usul (floor):", b1)
print("2-usul (trunc):", b2)
print("3-usul (astype):", b3)
print("4-usul (fix):", b4)


Asl massiv:
 [6.51637702 2.62285782 3.50206014 3.74260555 4.04060456 2.40291815
 4.0608851  7.40382388 9.47364967 7.01133917]

1-usul (floor): [6. 2. 3. 3. 4. 2. 4. 7. 9. 7.]
2-usul (trunc): [6. 2. 3. 3. 4. 2. 4. 7. 9. 7.]
3-usul (astype): [6 2 3 3 4 2 4 7 9 7]
4-usul (fix): [6. 2. 3. 3. 4. 2. 4. 7. 9. 7.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [2]:
a = np.arange(3) # 0,1,2
a = np.tile(a,(3,1))
print(a)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [5]:
a = np.arange(9).reshape(3,3)
a = a % 3
print(a)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [8]:
a = np.random.rand(10)
print(np.sort(a))

[0.07000175 0.24368121 0.27039871 0.41352754 0.5080522  0.72559704
 0.77311207 0.87541917 0.95698289 0.98136085]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [14]:
A = np.random.random((3,3))
B = np.random.random((3,3))

print("A = ", A)
print("B = ", B)

A =  [[0.55333085 0.88503648 0.17259634]
 [0.37802157 0.95905807 0.73077464]
 [0.70237327 0.38197868 0.6604122 ]]
B =  [[0.77444785 0.58041386 0.346537  ]
 [0.49918607 0.93928462 0.40517594]
 [0.33200833 0.61543024 0.28628853]]


In [16]:
print(np.array_equal(A,B))
print(np.allclose(A,B))

False
False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [19]:
a = np.ones(shape = (6, 3))
b = np.ones(shape = (3, 4))
print("a ",a)
print("____________________")
print("b ",b)

a  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
____________________
b  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
result = np.dot(a,b)
result

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [32]:
arr = np.random.rand(5)
w = np.argmax(arr)
w

np.int64(0)

In [35]:
arr[w] = 0
arr

array([0.        , 0.86203942, 0.65805943, 0.26345204, 0.06939938])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [36]:
bugun = np.datetime64('today','D')
kecha = bugun - np.timedelta64(1,'D')
erta = bugun + np.timedelta64(1,'D')

print(bugun)
print(kecha)
print(erta)

2025-10-24
2025-10-23
2025-10-25


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [37]:
sabalar = np.arange('2016-01-01','2016-02-01',dtype='datetime64[D]')
print(sabalar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [39]:
arr = np.random.random(5) * 10
print(arr)

butun1 = arr - arr % 1
butun2 = np.floor(arr)
butun3 = arr.astype(int)
butun4 = np.trunc(arr)



print("\n1-usul (% bilan):", butun1)
print("2-usul (floor bilan):", butun2)
print("3-usul (astype bilan):", butun3)
print("4-usul (trunc bilan):", butun4)

[5.54319461 2.96071347 9.95175408 8.35624335 0.10508192]

1-usul (% bilan): [5. 2. 9. 8. 0.]
2-usul (floor bilan): [5. 2. 9. 8. 0.]
3-usul (astype bilan): [5 2 9 8 0]
4-usul (trunc bilan): [5. 2. 9. 8. 0.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [47]:
arr1 = np.random.randint(1,10,size=5)
arr2 = np.random.randint(1,10,size=5)



sum1 = np.sum(arr1)
sum2 = np.sum(arr2)
print(sum1)
print(sum2)


print("______________________________")


sum3 = np.add.reduce(arr1)
sum4 = np.add.reduce(arr2)

print(sum3)
print(sum4)

19
25
______________________________
19
25


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [49]:
vec = np.array([1,2,3,4,5])

n = len(vec)
result = np.zeros(n + (n - 1) * 3, dtype = int)

result[::4] = vec
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [51]:
from numpy.lib.stride_tricks import as_strided

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

window_size = 4

b = as_strided(a
               ,shape=(len(a) - window_size + 1, window_size),
               strides=(a.strides[0],a.strides[0]))

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [60]:
arr = np.random.randint(10,size=20)
print(arr)
print("________________________________")

counts = np.bincount(arr)

most_comon = np.argmax(counts)
print(most_comon)
print(counts[most_comon])

[8 2 2 3 6 1 9 4 9 7 6 7 2 6 2 1 8 0 2 9]
________________________________
2
5
