In [ ]:
import numpy as np

In [17]:
arr = np.array([2,3,5])
print(arr)

[2 3 5]


In [18]:
print(type(arr))

<class 'numpy.ndarray'>


In [19]:
print(arr.shape)

(3,)


In [20]:
print(arr.dtype)

int64


In [33]:
arr = np.random.randint(1,10,size=2)
print(arr)

[8 3]


In [34]:
arr = np.array([
    [2,3,4],
    [5,6,7]
])
print(arr)

[[2 3 4]
 [5 6 7]]


In [37]:
arr = np.array([2,3,4,5,6],ndmin=2)
print(arr.shape)
print(arr)

(1, 5)
[[2 3 4 5 6]]


In [43]:
arr = np.random.randint(10,size=5)
print(arr)
print(arr[0])

[5 4 9 5 4]
5


In [45]:
arr[2] = 1
arr[2]

np.int32(1)

In [ ]:
r = np.random.randint(100,size=(3,4))
r

array([[30, 65, 79, 24],
       [90, 30, 19, 43],
       [87, 58,  1, 29]], dtype=int32)

In [53]:
r[-1,-1] = 4
r

array([[30, 65, 79, 24],
       [ 4, 30, 19, 43],
       [87, 58,  1,  4]], dtype=int32)

In [58]:
r = np.random.randint(100,size=10)
r

array([60, 65, 92, 38, 90, 29, 13, 17, 27, 99], dtype=int32)

In [59]:
r[1:4]

array([65, 92, 38], dtype=int32)

In [60]:
r[1:]

array([65, 92, 38, 90, 29, 13, 17, 27, 99], dtype=int32)

In [64]:
r[:5]

array([60, 65, 92, 38, 90], dtype=int32)

In [65]:
r[-1:]

array([99], dtype=int32)

In [66]:
r[:-1]

array([60, 65, 92, 38, 90, 29, 13, 17, 27], dtype=int32)

In [72]:
r[::2]

array([60, 92, 90, 13, 27], dtype=int32)

In [71]:
r[-6::2]

array([90, 13, 27], dtype=int32)

In [74]:
r = np.random.randint(100,size=(5,4))
r

array([[ 1, 61, 21, 56],
       [45, 32, 96, 79],
       [92, 65, 59, 75],
       [67, 35, 74, 42],
       [ 4,  5,  5, 82]], dtype=int32)

In [81]:
r[::-1]

array([[ 4,  5,  5, 82],
       [67, 35, 74, 42],
       [92, 65, 59, 75],
       [45, 32, 96, 79],
       [ 1, 61, 21, 56]], dtype=int32)