In [2]:
import numpy as np

In [17]:
a = np.random.randint(20, size = 10)
b = np.random.randint(20, size = 10)

print(a)
print()
print(b)

[12 19  0  3  7  1 14 13  4  9]

[ 0 10  4 17  5 15 16 16 15  0]


In [11]:
for i in range(a.shape[0]):
    c = a[i] + b[i]

In [14]:
c = a + b
print(c)

[18 20 21 ... 33 18 19]


In [15]:
c = a - b
print(c)

[-12  16 -15 ...   5  -8   1]


In [16]:
c = a / b
print(c)

[0.2        9.         0.16666667 ... 1.35714286 0.38461538 1.11111111]


C:\Users\behru\AppData\Local\Temp\ipykernel_23872\1994184757.py:1: RuntimeWarning: divide by zero encountered in divide
  c = a / b
C:\Users\behru\AppData\Local\Temp\ipykernel_23872\1994184757.py:1: RuntimeWarning: invalid value encountered in divide
  c = a / b


In [18]:
c = a * b
print(c)

[  0 190   0  51  35  15 224 208  60   0]


In [22]:
a = np.random.randint(20,size=11)
b = np.random.randint(20,size=10)
c = a * b
print(c)

ValueError: operands could not be broadcast together with shapes (11,) (10,) 

In [26]:
a = np.random.randint(20, size = 10)
b = np.random.randint(20, size = 10)

print(a)
print()
print(b)

[14 15  0  1  1 16 11 17  8  8]

[12 14  7  6 18 14  0  5 18  5]


In [29]:
c = a * 5
print(c)

[70 75  0  5  5 80 55 85 40 40]


In [30]:
c = a ** 2
print(c)

[196 225   0   1   1 256 121 289  64  64]


In [31]:
c = c % 2
print(c)

[0 1 0 1 1 0 1 1 0 0]


In [32]:
c = a // 2
print(c)

[7 7 0 0 0 8 5 8 4 4]


In [34]:
print(a)
c = np.exp(a)
print(c)

[14 15  0  1  1 16 11 17  8  8]
[1.20260428e+06 3.26901737e+06 1.00000000e+00 2.71828183e+00
 2.71828183e+00 8.88611052e+06 5.98741417e+04 2.41549528e+07
 2.98095799e+03 2.98095799e+03]


In [36]:
print(a)
c = np.abs(a)
print(c)

[14 15  0  1  1 16 11 17  8  8]
[14 15  0  1  1 16 11 17  8  8]


In [38]:
print(a)
c = np.sum(a)
print(c)

[14 15  0  1  1 16 11 17  8  8]
91


In [40]:
print(a)
c = np.max(a)
print(c)

[14 15  0  1  1 16 11 17  8  8]
17


In [41]:
a = np.random.randint(20, size = 10)
b = np.random.randint(20, size = 10)

print(a)
print()
print(b)

[19  0  7  0  4  0  8  0  5  2]

[ 3  7 18  7 18 17  4  8  9  7]


In [ ]:
# Sikaliyar ko'paytma
print(np.dot(a, b))
print(np.sum(a * b))
print(np.inner(a, b))

346
346
346


In [ ]:
# outer -> tashqi ko'paytma yani a ni b ni barcha qiymatiga ko'yaptiuradi qadamma qadam
C = np.outer(a, b)
print(C)

[[ 57 133 342 133 342 323  76 152 171 133]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 21  49 126  49 126 119  28  56  63  49]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 12  28  72  28  72  68  16  32  36  28]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 24  56 144  56 144 136  32  64  72  56]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 15  35  90  35  90  85  20  40  45  35]
 [  6  14  36  14  36  34   8  16  18  14]]


In [49]:
print(a)
c = np.all(a)
print(c)

[19  0  7  0  4  0  8  0  5  2]
False


In [58]:
print(a)
print(b)
c = a != b
print(c)

[19  0  7  0  4  0  8  0  5  2]
[ 3  7 18  7 18 17  4  8  9  7]
[ True  True  True  True  True  True  True  True  True  True]


In [61]:
a = np.random.randint(2, size=(10, ), dtype = np.bool)
b = np.random.randint(2, size=(10, ), dtype = np.bool)

print(a)
print()
print(b)


[ True  True  True False  True  True False False False  True]

[ True  True  True  True False  True False  True False  True]


In [65]:
# yantiqiy va  yani 0 && 1 = 0 , 1 && 1 = 1 --> 0 qatnashsa  0 bo'ladi
c = np.logical_and(a,b)
print(c)

[ True  True  True False False  True False False False  True]


In [ ]:
# Mantiqiy || yoki yani 0 || 1 = 1 , 0 || 0 = 0 , 1 || 1 = 1 mantiqiy yoki bitta rost qatnas bo'ldi rost bo'ladi
c = np.logical_or(a,b)
print(c)

[ True  True  True  True  True  True False  True False  True]


In [ ]:
# not operatori unar operator 
c = np.logical_not(a)
print(c)

[False False False  True False False  True  True  True False]


In [70]:
c = a
c is a

True

In [79]:
a = np.random.randint(20, size = 10)
b = np.random.randint(20, size = 10)

print(a)
print()
print(b)

[10  1  9  3 15 13  0 14  2 15]

[ 7  4  1  5 17  6 11  5 16  1]


In [78]:
71 in a

False

In [77]:
print(a)
c = np.cos(a)
print(c)

[ 3  0  1 19 17 13 13 15 12  7]
[-0.9899925   1.          0.54030231  0.98870462 -0.27516334  0.90744678
  0.90744678 -0.75968791  0.84385396  0.75390225]


In [ ]:
A = np.random.randint(20, size = (4,3))
B = np.random.randint(20, size = (4,3))

print(A)
print()
print(B)

[[12  7  5]
 [14  9 12]
 [12  3 11]
 [ 8 18  6]]

[[14  4  6]
 [ 0  7 16]
 [ 9  4  3]
 [ 1 10  6]]


In [91]:
C = A + B
print(C)

[[26 11 11]
 [14 16 28]
 [21  7 14]
 [ 9 28 12]]


In [92]:
C = A - B
print(C)

[[-2  3 -1]
 [14  2 -4]
 [ 3 -1  8]
 [ 7  8  0]]


In [95]:
C = A * B
print(C)

[[168  28  30]
 [  0  63 192]
 [108  12  33]
 [  8 180  36]]


In [94]:
C = A / B
print(C)

[[0.85714286 1.75       0.83333333]
 [       inf 1.28571429 0.75      ]
 [1.33333333 0.75       3.66666667]
 [8.         1.8        1.        ]]


C:\Users\behru\AppData\Local\Temp\ipykernel_23872\3909228385.py:1: RuntimeWarning: divide by zero encountered in divide
  C = A / B


In [96]:
C = A == B
print(C)

[[False False False]
 [False False False]
 [False False False]
 [False False  True]]


In [98]:
A = np.random.randint(20, size = (4, 3, 2))
B = np.random.randint(20, size = (4, 3, 2))

print(A)
print("-------------------------------------------")
print(B)

[[[14  0]
  [ 6 14]
  [15 13]]

 [[ 4  3]
  [12  7]
  [ 6 13]]

 [[15  5]
  [10 10]
  [ 4  1]]

 [[15 10]
  [ 5  5]
  [ 3  3]]]
-------------------------------------------
[[[ 7 10]
  [10  9]
  [16  4]]

 [[13  0]
  [ 6  4]
  [ 6  6]]

 [[14  8]
  [19 12]
  [11  6]]

 [[ 2 16]
  [11 14]
  [12  2]]]


In [99]:
C = A + B
print(C)

[[[21 10]
  [16 23]
  [31 17]]

 [[17  3]
  [18 11]
  [12 19]]

 [[29 13]
  [29 22]
  [15  7]]

 [[17 26]
  [16 19]
  [15  5]]]


In [108]:
# matrissani matrissaga ko'paytirish uchun 
A = np.random.randint(20, size = (5, 3))
B = np.random.randint(20, size = (3, 4))

print(A)
print("___________________________________")
print(B)

[[18  1  8]
 [ 2 11 16]
 [ 2  8  9]
 [12  1 13]
 [18  0  4]]
___________________________________
[[14  6 10  5]
 [11 18 16  1]
 [ 0 17  1  8]]


In [109]:
C = np.matmul(A, B)
print(C)

[[263 262 204 155]
 [149 482 212 149]
 [116 309 157  90]
 [179 311 149 165]
 [252 176 184 122]]


In [110]:
# matrissani matrissaga ko'paytirish uchun 
A = np.random.randint(20, size = (5, 3))
B = np.random.randint(20, size = (3, 4))

print(A)
print("___________________________________")
print(B)

[[ 2  8  8]
 [ 7  5  8]
 [10 13 18]
 [16  5 13]
 [16  5  1]]
___________________________________
[[12  1  3 14]
 [10  9 11  2]
 [ 0  3 12  5]]


In [ ]:
# matrissa qatorlar yig'indisi
np.sum(A,axis=1)

array([18, 20, 41, 34, 22])

In [113]:
# matrisa ustunlar yi'g'indisi
np.sum(A, axis = 0)

array([51, 36, 48])

In [114]:
np.max(A)

np.int32(18)

In [115]:
np.argmax(A)

np.int64(8)

In [116]:
np.max(A,axis=1)

array([ 8,  8, 18, 16, 16], dtype=int32)

In [117]:
np.argmax(A, axis = 1)

array([1, 2, 2, 0, 0])

In [119]:
print(np.mean(A))

9.0


In [120]:
print(np.std(A))

5.033222956847166


In [121]:
print(np.var(A))

25.333333333333332


In [122]:
print(np.std(A, axis = 0))

[5.38144962 3.12409987 5.67802783]


In [123]:
# matrissani matrissaga ko'paytirish uchun 
A = np.random.randint(20, size = (5, 3, 4))

print(A)
print("___________________________________")

[[[ 0  3  0 10]
  [16 13  7 10]
  [19  6 15  5]]

 [[ 7 15 13  2]
  [ 4 10 18 15]
  [13  9 17 19]]

 [[ 9  7  7  3]
  [10 15 16 10]
  [15  9  9 18]]

 [[11  5  1  0]
  [ 3 16 15 17]
  [11 19 16  6]]

 [[10 19 19  6]
  [14  5  5  4]
  [ 7  2  0 11]]]
___________________________________


In [ ]:
print(np.sum(A,axis=0))

596


In [127]:
print(np.sum(A, axis = 1))

[[35 22 22 25]
 [24 34 48 36]
 [34 31 32 31]
 [25 40 32 23]
 [31 26 24 21]]


In [128]:
print(np.sum(A, axis = 2))

[[13 46 45]
 [37 47 58]
 [26 51 51]
 [17 51 52]
 [54 28 20]]


In [130]:
A = np.random.randint(20, size = (5, 3))

print(A)

[[15  8  5]
 [ 7 19  8]
 [14 10  1]
 [ 4  0 17]
 [ 7 18 11]]


In [131]:
A.T

array([[15,  7, 14,  4,  7],
       [ 8, 19, 10,  0, 18],
       [ 5,  8,  1, 17, 11]], dtype=int32)

In [186]:
A = np.random.randint(20, size = (5, 3))
c = A.ravel()
print(c)

[ 0 18  2  0  8  5  1  3 18  0 14  1  7 12 11]


In [196]:
np.save('A.npy' ,A)
np.savetxt('A.txt', A, fmt = "%d")

In [195]:
A = np.load('A.npy')
A

array([[ 0., 18.,  2.],
       [ 0.,  8.,  5.],
       [ 1.,  3., 18.],
       [ 0., 14.,  1.],
       [ 7., 12., 11.]])

In [1]:
import numpy as np

In [3]:
A = np.load('A.npy')
A

array([[ 0., 18.,  2.],
       [ 0.,  8.,  5.],
       [ 1.,  3., 18.],
       [ 0., 14.,  1.],
       [ 7., 12., 11.]])

In [4]:
a = np.array([0, 1, 2])

In [5]:
B = A + a
B

array([[ 0., 19.,  4.],
       [ 0.,  9.,  7.],
       [ 1.,  4., 20.],
       [ 0., 15.,  3.],
       [ 7., 13., 13.]])

In [12]:
b = np.array([1, 1, 2, 3, 4]).reshape((5, 1))
b

array([[1],
       [1],
       [2],
       [3],
       [4]])

In [10]:
A

array([[ 0., 18.,  2.],
       [ 0.,  8.,  5.],
       [ 1.,  3., 18.],
       [ 0., 14.,  1.],
       [ 7., 12., 11.]])

In [9]:
C = A + b
C

array([[ 0., 18.,  2.],
       [ 1.,  9.,  6.],
       [ 3.,  5., 20.],
       [ 3., 17.,  4.],
       [11., 16., 15.]])

In [13]:
C = A / b
C

array([[ 0.        , 18.        ,  2.        ],
       [ 0.        ,  8.        ,  5.        ],
       [ 0.5       ,  1.5       ,  9.        ],
       [ 0.        ,  4.66666667,  0.33333333],
       [ 1.75      ,  3.        ,  2.75      ]])

In [14]:
C = A * b
C

array([[ 0., 18.,  2.],
       [ 0.,  8.,  5.],
       [ 2.,  6., 36.],
       [ 0., 42.,  3.],
       [28., 48., 44.]])

In [ ]:
X = np.random.rand(100, 5)
X

array([[4.45412685e-01, 2.48187210e-01, 7.03661130e-01, 8.81454827e-01,
        8.56222554e-01],
       [6.33385112e-01, 1.45815844e-01, 4.18931588e-01, 9.17526106e-01,
        6.52333106e-01],
       [8.76433745e-01, 3.84484615e-01, 5.37609763e-01, 2.87244504e-01,
        6.70768461e-01],
       [6.42221263e-01, 8.79520578e-01, 8.76833017e-01, 6.06361738e-01,
        6.76884229e-01],
       [7.92127456e-01, 7.88496524e-01, 8.67061612e-02, 2.33676229e-01,
        3.30879211e-01],
       [5.77894808e-01, 2.20994165e-01, 9.70610561e-01, 4.74329543e-01,
        8.34342856e-01],
       [4.29483493e-01, 8.19661181e-01, 4.71586760e-02, 7.92801308e-01,
        2.16958938e-01],
       [6.98956049e-01, 5.23856733e-01, 4.58767278e-01, 3.42225708e-01,
        1.22967247e-01],
       [2.37519932e-01, 7.01302501e-01, 3.91707318e-01, 7.49253397e-01,
        1.91697801e-01],
       [6.42635025e-01, 2.76534955e-01, 4.61802976e-01, 9.01707900e-01,
        6.38826789e-01],
       [7.02953541e-01, 8.2470

In [ ]:
row_sum = np.sum(X, axis = 1)
row_sum

array([3.13493841, 2.76799176, 2.75654109, 3.68182083, 2.23188558,
       3.07817193, 2.3060636 , 2.14677302, 2.27148095, 2.92150764,
       3.23390448, 1.62839033, 3.05001991, 3.25907826, 1.97305596,
       2.94242094, 2.45730876, 4.29847046, 3.46288368, 3.47610558,
       3.44846049, 1.92746903, 2.48764913, 3.65578195, 3.2460031 ,
       2.89903405, 2.75731895, 1.98750278, 3.38194753, 2.92153636,
       2.94903508, 3.02939323, 1.72356465, 2.24147514, 1.96526517,
       2.81426731, 2.43366018, 1.60061151, 1.92339965, 4.33493167,
       2.67114972, 3.01778786, 2.19211882, 2.76198614, 1.61827321,
       1.33189487, 2.24226785, 2.1536699 , 2.96833673, 1.78322889,
       2.42277817, 2.04711299, 3.50961168, 2.53733932, 2.60802801,
       3.29100773, 1.52644875, 2.48240204, 1.76436616, 2.29020786,
       2.67912632, 2.17058096, 2.23762181, 2.37529468, 2.08136966,
       2.91570888, 2.96241857, 2.93987243, 2.97851828, 1.73857051,
       3.72530247, 3.046078  , 3.30785875, 2.30310137, 2.75598

In [ ]:
X = np.random.rand(100, 5)
exp_X = np.exp(X)
row_sum = np.sum(exp_X, axis = 1, keepdims = True)
probs = exp_X /  row_sum

In [54]:
print(probs[0])

[0.27253049 0.12912226 0.19580178 0.18003341 0.22251206]
