In [6]:
import numpy as np

In [ ]:
# ikkiga to'rt massiv zeros orqali 0 bilan topshiramiz
a = np.zeros(shape=(2,4))
b = np.zeros_like(a)
b = np.zeros(shape=a.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a = np.ones(shape=(2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a = np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.linspace(0,1,200)
a

array([0.        , 0.00502513, 0.01005025, 0.01507538, 0.0201005 ,
       0.02512563, 0.03015075, 0.03517588, 0.04020101, 0.04522613,
       0.05025126, 0.05527638, 0.06030151, 0.06532663, 0.07035176,
       0.07537688, 0.08040201, 0.08542714, 0.09045226, 0.09547739,
       0.10050251, 0.10552764, 0.11055276, 0.11557789, 0.12060302,
       0.12562814, 0.13065327, 0.13567839, 0.14070352, 0.14572864,
       0.15075377, 0.15577889, 0.16080402, 0.16582915, 0.17085427,
       0.1758794 , 0.18090452, 0.18592965, 0.19095477, 0.1959799 ,
       0.20100503, 0.20603015, 0.21105528, 0.2160804 , 0.22110553,
       0.22613065, 0.23115578, 0.2361809 , 0.24120603, 0.24623116,
       0.25125628, 0.25628141, 0.26130653, 0.26633166, 0.27135678,
       0.27638191, 0.28140704, 0.28643216, 0.29145729, 0.29648241,
       0.30150754, 0.30653266, 0.31155779, 0.31658291, 0.32160804,
       0.32663317, 0.33165829, 0.33668342, 0.34170854, 0.34673367,
       0.35175879, 0.35678392, 0.36180905, 0.36683417, 0.37185

In [20]:
a = np.zeros(shape=(3,3))
np.fill_diagonal(a,val=1)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
a = np.random.rand(3,4)
a

array([[0.65783615, 0.91491864, 0.01429508, 0.73338818],
       [0.42747483, 0.7587838 , 0.1168299 , 0.67637812],
       [0.63343642, 0.14677211, 0.98584824, 0.31911946]])

In [23]:
a[0] = np.zeros(4)
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.34600008, 0.53822582, 0.05863986, 0.45140546],
       [0.76037099, 0.1390116 , 0.50553138, 0.8464323 ]])

In [58]:
a[:,0] = np.zeros(3)
a

array([[0.        , 0.91491864, 0.01429508, 0.73338818],
       [0.        , 0.7587838 , 0.1168299 , 0.67637812],
       [0.        , 0.14677211, 0.98584824, 0.31911946]])

In [62]:
a[::2] = np.zeros(shape=(2,4))
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.7587838 , 0.1168299 , 0.67637812],
       [0.        , 0.        , 0.        , 0.        ]])

In [63]:
a.dtype

dtype('float64')

In [65]:
b = a.astype(np.float32)
b.dtype

dtype('float32')

In [69]:
np.allclose(b, a)

True

In [75]:
np.zeros(4, dtype = np.int8).astype(bool)

array([False, False, False, False])

In [ ]:
a = np.random.rand(4,3)         
a

array([[0.97966381, 0.07549354, 0.36051113],
       [0.90351879, 0.32838325, 0.20398083],
       [0.3935375 , 0.44559629, 0.45373722],
       [0.35117038, 0.13408827, 0.08520033]])

In [80]:
a = a.view(dtype=np.int32)
a

array([[-384955749, 1072650599, 1607541608, 1068716939, 1092976538,
        1071059613],
       [ 998376263, 1072490912,  721464472, 1070924859, 1055478300,
        1070210059],
       [-417409864, 1071198135, 1282915976, 1071416486, -697749190,
        1071450631],
       [1468474148, 1071020435, -433356436, 1069623757, 1211823624,
        1068879792]], dtype=int32)

In [81]:
b = a.copy()
b

array([[-384955749, 1072650599, 1607541608, 1068716939, 1092976538,
        1071059613],
       [ 998376263, 1072490912,  721464472, 1070924859, 1055478300,
        1070210059],
       [-417409864, 1071198135, 1282915976, 1071416486, -697749190,
        1071450631],
       [1468474148, 1071020435, -433356436, 1069623757, 1211823624,
        1068879792]], dtype=int32)

In [122]:
a = np.arange(12)
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a = np.arange(12)
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a = np.arange(12)
b = a.reshape(3, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [126]:
class MyIter:

    def __iter__(self):
        for i in range(10):
            yield i

In [ ]:
for i in MyIter():
    print(i)

0
1
2
3
4
5
6
7
8
9


In [135]:
for i in np.arange(12).reshape(3,4):
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
# bir olchovli matrissani birrriga bo'glash 
a = np.arange(5)
b = np.arange(6)
c = np.concatenate((a,b))
c

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [ ]:
# matrissalarni birbiriga bog'lash 2 olchovli
a = np.arange(12).reshape(3,4)
b = np.arange(8).reshape(2,4)
c = np.concatenate((a,b))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [142]:
# Endi buni ustuni birxil satir turli xil
# bunga aytamiz 1 chi bo'yicha to'ldir
a = np.arange(12).reshape(4,3)
b = np.arange(8).reshape(4,2)
c = np.concatenate((a,b), axis=1)
c

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7]])

In [ ]:
# Endi matrissani bo'glashni stack orqali o'rganamiz
a = np.arange(5)
b = np.arange(5)
c = np.stack((a,b))
c

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [145]:
a = np.arange(12).reshape(4, 3)
b = np.arange(12).reshape(4, 2)
c = np.stack((a, b), axis = 1)
c

ValueError: cannot reshape array of size 12 into shape (4,2)

In [150]:
a = np.arange(12)
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [151]:
a = np.arange(12)
np.where(a == 4)

(array([4]),)

In [158]:
a = np.array([2,5,4,0,5,4,7])
np.where(a == 4)

(array([2, 5]),)

In [159]:
b = np.random.randint(12,size=(3,4))
np.where(b == 9)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
a = np.array([2,5,4,0,5,4,7])
np.sort(a)
print(a)

[2 5 4 0 5 4 7]


In [167]:
a = np.array([2,5,4,0,5,4,7])
np.argsort(a)


array([3, 0, 2, 5, 1, 4, 6])

In [ ]:
# min minumunnini topip beradi
a = np.array([2,5,4,0,5,4,7])
np.min(a)

np.int64(0)

In [ ]:
# min yani minimalini index ni beradi
a = np.array([2,5,4,0,5,4,7])
np.argmin(a)

np.int64(3)

In [ ]:
# max maxsimalini index ni beradi 
a = np.array([2,5,4,0,5,4,7])
np.argmax(a)

np.int64(6)

In [ ]:
# max maxsimalini indexini ber
a = np.array([2,5,4,0,5,4,7])
np.max(a)

np.int64(7)

In [181]:
a = np.array([2,5,4,0,5,4,7])
np.sin(a)

array([ 0.90929743, -0.95892427, -0.7568025 ,  0.        , -0.95892427,
       -0.7568025 ,  0.6569866 ])

In [182]:
a = np.array([2,5,4,0,5,4,7])
a[a == 4] = 20
a

array([ 2,  5, 20,  0,  5, 20,  7])

In [ ]:
a = np.array([2,5,4,0,5,4,7])
a[a % 2 == 0] = 10
a

array([ 2, 10,  4,  0, 10,  4, 10])

In [ ]:
a = np.array([1,3,4,5,6,3])
np.where(a == 3)

6
