In [1]:
import numpy as np

In [2]:
my_list = list(range(100000))
my_array = np.array(range(100000))

In [3]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [4]:
my_array

array([    0,     1,     2, ..., 99997, 99998, 99999], shape=(100000,))

In [ ]:
%time for _ in range(10): [x * 2 for x in my_list] # Normal

CPU times: total: 62.5 ms
Wall time: 76.2 ms


In [ ]:
%time for _ in range(10): my_array * 2 # wektorlashgan

CPU times: total: 0 ns
Wall time: 2.78 ms


In [46]:
%time for _ in range(10): my_array * 2

CPU times: total: 0 ns
Wall time: 3.02 ms


In [7]:
76.2 / 2.78

27.410071942446045

In [11]:
%time for _ in range(10) : [x * 2 for x in my_list]

CPU times: total: 93.8 ms
Wall time: 74.2 ms


In [13]:
%time for _ in range(10): my_array * 2

CPU times: total: 0 ns
Wall time: 789 μs


In [25]:
data1 = [3,4,5,6,6]
arr1 = np.array(data1)
arr1

array([3, 4, 5, 6, 6])

In [26]:
data2 = (2,3,4,5,6)
arr2 = np.array(data2)
arr2

array([2, 3, 4, 5, 6])

In [ ]:
arr1.ndim # massiv o'lchami

1

In [ ]:
arr2.ndim # massiv o'lchami

1

In [ ]:
data3 = [[1,2,3,4],[5,6,7,8]] # list ichidagi list (nested list) - > 2 o'lchamili 
arr3 = np.array(data3)
arr3.ndim

2

In [ ]:
data4 = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]] # 3 o'lchamli massiv
arr4 = np.array(data4)
arr4.ndim

3

In [ ]:
arr3.shape # qator va ustunlar so'ni

(2, 4)

In [ ]:
arr3.size # array3 ning elementlar soni 

8

In [ ]:
arr5 = np.zeros(shape=(3,4)) # barcha elementlari  0 ga teng
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr6 = np.zeros(shape=(2,3))
arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr7 = np.ones(shape=(2,3)) # barcha elementlari 1 ga teng
arr7

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr8 = np.arange(4,20,2) # boshlanish qadam 2, maksimal 20
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr9 = np.arange(20) # bir boshdan chiqarib beradi
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
arr9.shape

(20,)

In [44]:
arr5.shape

(3, 4)

In [45]:
arr5.size

12

In [48]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [49]:
arr2 = np.array([1,2,3],dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [50]:
arr1.dtype

dtype('float64')

In [51]:
arr2.dtype

dtype('int32')

In [52]:
arr = np.array([1,2,3,4]) # 
arr

array([1, 2, 3, 4])

In [54]:
arr.dtype

dtype('int64')

In [55]:
float_arr = arr.astype(np.float64)

In [57]:
float_arr.dtype

dtype('float64')

In [60]:
data = np.array([3,4,5,6])
data.dtype

dtype('int64')

In [4]:
import numpy as np

In [5]:
arr = np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
arr[0]

np.int64(10)

In [7]:
arr[3]

np.int64(40)

In [8]:
arr[-2]

np.int64(80)

In [9]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0

In [13]:
sliced_arr

array([0, 0])

In [14]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [20]:
arr1 = np.arange(10,100,10)

In [21]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0

In [23]:
sliced_arr1

array([0, 0])

In [24]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # (3, 3) o'lchamli massiv

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2.shape

(3, 3)

In [29]:
arr2.size

9

In [30]:
arr2.ndim

2

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2[1,1]

np.int64(5)

In [34]:
arr2[2,2]

np.int64(9)

In [37]:
sl_arr2d = arr2[2,1:3]
sl_arr2d

array([8, 9])

In [38]:
arr3d = np.array([[[0,1,2]
                   ,[3,4,5]
                   ,[6,7,8]],
                   
                   [[9,10,11]
                    ,[12,13,14]
                    ,[15,16,17]],
                    
                    [[18,19,20],
                     [21,22,23],
                     [24,25,26]]])

In [39]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
arr3d[0][1,1]

np.int64(4)

In [90]:
arr3d.shape

(3, 3, 3)

In [45]:
arr3d[1][2,1:]

array([16, 17])

In [43]:
arr3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [44]:
arr3d[2][1,2]

np.int64(23)

In [46]:
arr3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [47]:
arr3d[2][0, :2]

array([18, 19])

In [48]:
import numpy as np

In [54]:
names = np.array(['ali','bali','akbar','vali'])
names

array(['ali', 'bali', 'akbar', 'vali'], dtype='<U5')

In [55]:
data = np.random.rand(4,3)
data

array([[0.62743002, 0.94637464, 0.47145528],
       [0.79696039, 0.49396455, 0.40446504],
       [0.43966663, 0.40721947, 0.45339757],
       [0.54421133, 0.52996911, 0.81108764]])

In [57]:
names == 'ali'

array([ True, False, False, False])

In [59]:
data[names == 'ali'] # Hasanga tegishli barcha malumotlar 

array([[0.62743002, 0.94637464, 0.47145528]])

In [ ]:
data[names == 'vali'] # Elyorga tegilshiu barchamalumotlarini ajaratib olish

array([[0.54421133, 0.52996911, 0.81108764]])

In [ ]:
data[names == 'ali',1:]   # alidagi malumotlar

array([[0.94637464, 0.47145528]])

In [ ]:
data[names != 'ali'] # alidan tashqari barcha insonlar olish

array([[0.79696039, 0.49396455, 0.40446504],
       [0.43966663, 0.40721947, 0.45339757],
       [0.54421133, 0.52996911, 0.81108764]])

In [63]:
data[names != 'bali']

array([[0.62743002, 0.94637464, 0.47145528],
       [0.43966663, 0.40721947, 0.45339757],
       [0.54421133, 0.52996911, 0.81108764]])

In [64]:
data[names == 'bali',1:]

array([[0.49396455, 0.40446504]])

In [68]:
print(data)
print(names)

[[0.62743002 0.94637464 0.47145528]
 [0.79696039 0.49396455 0.40446504]
 [0.43966663 0.40721947 0.45339757]
 [0.54421133 0.52996911 0.81108764]]
['ali' 'bali' 'akbar' 'vali']


In [71]:
name1 = np.array(['behruz','behzod','alisher','sherzod'])
name1

array(['behruz', 'behzod', 'alisher', 'sherzod'], dtype='<U7')

In [73]:
data1 = np.random.rand(4,5)
data1

array([[0.37866477, 0.06580733, 0.93500057, 0.6013557 , 0.50562094],
       [0.83704364, 0.13835778, 0.04535988, 0.79858105, 0.64164975],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804],
       [0.84394258, 0.05390206, 0.38335087, 0.4668589 , 0.01922612]])

In [74]:
data1[name1 == 'behruz']

array([[0.37866477, 0.06580733, 0.93500057, 0.6013557 , 0.50562094]])

In [75]:
data1[name1 != 'behruz']

array([[0.83704364, 0.13835778, 0.04535988, 0.79858105, 0.64164975],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804],
       [0.84394258, 0.05390206, 0.38335087, 0.4668589 , 0.01922612]])

In [76]:
data1[name1 == 'behruz',2:]

array([[0.93500057, 0.6013557 , 0.50562094]])

In [78]:
data1[~(name1 == 'behruz')]

array([[0.83704364, 0.13835778, 0.04535988, 0.79858105, 0.64164975],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804],
       [0.84394258, 0.05390206, 0.38335087, 0.4668589 , 0.01922612]])

In [81]:
print(name1)
print(data1)

['behruz' 'behzod' 'alisher' 'sherzod']
[[0.37866477 0.06580733 0.93500057 0.6013557  0.50562094]
 [0.83704364 0.13835778 0.04535988 0.79858105 0.64164975]
 [0.52665016 0.77904404 0.47342886 0.32667148 0.66112804]
 [0.84394258 0.05390206 0.38335087 0.4668589  0.01922612]]


In [82]:
mask = (name1 == 'behruz') | (name1 == "alisher")
mask

array([ True, False,  True, False])

In [83]:
data1[mask]

array([[0.37866477, 0.06580733, 0.93500057, 0.6013557 , 0.50562094],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804]])

In [84]:
data1

array([[0.37866477, 0.06580733, 0.93500057, 0.6013557 , 0.50562094],
       [0.83704364, 0.13835778, 0.04535988, 0.79858105, 0.64164975],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804],
       [0.84394258, 0.05390206, 0.38335087, 0.4668589 , 0.01922612]])

In [88]:
data1[data1 < 0] = 0

In [89]:
data1

array([[0.37866477, 0.06580733, 0.93500057, 0.6013557 , 0.50562094],
       [0.83704364, 0.13835778, 0.04535988, 0.79858105, 0.64164975],
       [0.52665016, 0.77904404, 0.47342886, 0.32667148, 0.66112804],
       [0.84394258, 0.05390206, 0.38335087, 0.4668589 , 0.01922612]])

In [1]:
import numpy as np

In [ ]:
A = np.arange(6).reshape(3,2) # Elementlari 0 dan 6 gacha ekan
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
B = np.arange(10).reshape(2,5)
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
C = np.arange(12).reshape(2,3,2)
C

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [11]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [15]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
w = np.dot(A,A.T) # AA^T hosil bo'lgan massiv 

In [17]:
w

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [18]:
arr = np.arange(10) # 0 ~ 10 gacha bo'lgan massiv qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
w = np.sqrt(arr)
w

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [21]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [23]:
np.log(arr) # arr nomli massivning barcha elementlarini lografimimi hisoblaydi

C:\Users\behru\AppData\Local\Temp\ipykernel_2172\3042305968.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # arr nomli massivning barcha elementlarini lografimimi hisoblaydi


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [24]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr1 = np.random.rand(6) 
arr1

array([0.59200738, 0.45769255, 0.72952868, 0.96014279, 0.07458504,
       0.91787901])

In [33]:
arr2 = np.random.rand(6).reshape(2,3)
arr2

array([[0.57643735, 0.26898876, 0.21653716],
       [0.18201551, 0.98668062, 0.51099849]])

In [31]:
arr1

array([0.79932177, 0.65700794, 0.63304004, 0.02661495, 0.68374145,
       0.87509265])

In [56]:
qoldiq,butun = np.modf(arr1)

In [57]:
print(qoldiq)
print(butun)

[0.59200738 0.45769255 0.72952868 0.96014279 0.07458504 0.91787901]
[0. 0. 0. 0. 0. 0.]


In [60]:
qoldiq,butun = np.modf(arr2)

In [61]:
print(qoldiq)
print(butun)

[[0.57643735 0.26898876 0.21653716]
 [0.18201551 0.98668062 0.51099849]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [62]:
arr1

array([0.59200738, 0.45769255, 0.72952868, 0.96014279, 0.07458504,
       0.91787901])

In [65]:
w = np.isnan(arr1)
w

array([False, False, False, False, False, False])

In [66]:
arr1[0] = np.nan

In [67]:
arr1

array([       nan, 0.45769255, 0.72952868, 0.96014279, 0.07458504,
       0.91787901])

In [69]:
w1 = np.isnan(arr1)
w1

array([ True, False, False, False, False, False])

In [70]:
arr3 = np.random.rand(6)
arr4 = np.random.rand(6)

In [71]:
arr3

array([0.64493124, 0.16223959, 0.71541068, 0.83903969, 0.80820174,
       0.78163962])

In [73]:
arr4

array([0.58769076, 0.81791491, 0.84861167, 0.17634763, 0.2904535 ,
       0.32485531])

In [ ]:
arr3

array([0.64493124, 0.16223959, 0.71541068, 0.83903969, 0.80820174,
       0.78163962])

In [76]:
np.add(arr3,arr4)  

array([1.23262199, 0.9801545 , 1.56402235, 1.01538732, 1.09865524,
       1.10649493])

In [77]:
arr3 + arr4

array([1.23262199, 0.9801545 , 1.56402235, 1.01538732, 1.09865524,
       1.10649493])

In [78]:
np.multiply(arr3,arr4)

array([0.37902013, 0.13269818, 0.60710585, 0.14796266, 0.23474503,
       0.25391978])

In [79]:
np.multiply(arr3,arr4)

array([0.37902013, 0.13269818, 0.60710585, 0.14796266, 0.23474503,
       0.25391978])

In [80]:
np.maximum(arr3,arr4)

array([0.64493124, 0.81791491, 0.84861167, 0.83903969, 0.80820174,
       0.78163962])

In [81]:
print(arr3)
print(arr4)

[0.64493124 0.16223959 0.71541068 0.83903969 0.80820174 0.78163962]
[0.58769076 0.81791491 0.84861167 0.17634763 0.2904535  0.32485531]


In [82]:
import numpy as np

In [84]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [85]:
cond = np.array([True,False,True,True,False])

In [87]:
result = np.where(cond,xarr,yarr) # cond turue bo'lsa x ni qiymatini oladi agar False bo'lsa y -> qiymatini oladi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [92]:
arr = np.random.rand(4,4)
arr

array([[0.1363072 , 0.0975888 , 0.04190713, 0.21490746],
       [0.84634705, 0.37033274, 0.75969942, 0.28764819],
       [0.55771197, 0.49894404, 0.36662612, 0.72315323],
       [0.70461822, 0.28645564, 0.59279026, 0.28215117]])

In [94]:
result = np.where(arr < 0, -2, 2) # arr ning manfiy elementlarini -2 ga musbatni 2 ga almashtirish
result

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [112]:
arr1 = np.random.rand(6,5)
arr1

array([[0.2814017 , 0.14352455, 0.11102329, 0.9567673 , 0.00445883],
       [0.85738076, 0.08875007, 0.52967789, 0.10981792, 0.24926321],
       [0.8225457 , 0.54250601, 0.47858756, 0.13854325, 0.67517361],
       [0.7960665 , 0.81313056, 0.19246774, 0.40120968, 0.6087528 ],
       [0.74975412, 0.45243935, 0.72482144, 0.16222067, 0.34051335],
       [0.95923463, 0.25111211, 0.38116778, 0.03816318, 0.98063864]])

In [113]:
result1 = np.where(arr1 < 0, -3, 3)
result1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [116]:
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([6,7,8,9,10])

In [117]:
cond = np.array([True,False,True,False,True])

In [119]:
result = np.where(cond,arr2,arr3)
result

array([1, 7, 3, 9, 5])

In [120]:
import numpy as np

In [123]:
# data 
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [124]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [126]:
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [127]:
arr2 / arr1

C:\Users\behru\AppData\Local\Temp\ipykernel_2172\2767132540.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2 / arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [128]:
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [129]:
arr2 + arr1

array([[ 6,  8, 10],
       [12, 14, 16]])

In [130]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [131]:
arr2**2

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [132]:
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [133]:
import numpy as np

In [135]:
arr = np.random.rand(5,4)
arr

array([[0.54457769, 0.63760796, 0.29660374, 0.87750205],
       [0.42593867, 0.98682339, 0.91320861, 0.26318822],
       [0.78882588, 0.84508091, 0.44180708, 0.91704456],
       [0.53619566, 0.74472209, 0.02881285, 0.20777546],
       [0.49445584, 0.46195482, 0.22604392, 0.06463117]])

In [136]:
arr.sum()

np.float64(10.702800577193969)

In [137]:
np.sum(arr)

np.float64(10.702800577193969)

In [ ]:
w = np.sum(arr,axis=1) # qaror yi'gindi
w

array([2.35629144, 2.58915889, 2.99275843, 1.51750606, 1.24708575])

In [ ]:
w1 = np.sum(arr,axis=0) # ustun yig'indi
w1 

array([2.78999374, 3.67618917, 1.90647619, 2.33014147])

In [141]:
arr

array([[0.54457769, 0.63760796, 0.29660374, 0.87750205],
       [0.42593867, 0.98682339, 0.91320861, 0.26318822],
       [0.78882588, 0.84508091, 0.44180708, 0.91704456],
       [0.53619566, 0.74472209, 0.02881285, 0.20777546],
       [0.49445584, 0.46195482, 0.22604392, 0.06463117]])

In [ ]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [145]:
mean = np.mean(data)
mean

np.float64(2.0)

In [146]:
arr

array([[0.54457769, 0.63760796, 0.29660374, 0.87750205],
       [0.42593867, 0.98682339, 0.91320861, 0.26318822],
       [0.78882588, 0.84508091, 0.44180708, 0.91704456],
       [0.53619566, 0.74472209, 0.02881285, 0.20777546],
       [0.49445584, 0.46195482, 0.22604392, 0.06463117]])

In [148]:
mean1 = np.mean(arr)
mean1

np.float64(0.5351400288596985)

In [150]:
mean2 = np.mean(arr,axis=1)
mean2

array([0.58907286, 0.64728972, 0.74818961, 0.37937651, 0.31177144])

In [152]:
mean3 = np.mean(arr,axis=0)
mean3

array([0.55799875, 0.73523783, 0.38129524, 0.46602829])

In [153]:
data

array([0, 1, 2, 3, 4])

In [154]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [155]:
data.cumprod()

array([0, 0, 0, 0, 0])

In [156]:
import numpy as n

In [ ]:
arr = np.random.rand(4) # taxminiy qiymat 4 ta
arr

array([0.57034945, 0.57040935, 0.79707351, 0.17746187])

In [159]:
w = np.sort(arr)
w

array([0.17746187, 0.57034945, 0.57040935, 0.79707351])

In [161]:
arr.sort()
arr

array([0.17746187, 0.57034945, 0.57040935, 0.79707351])

In [163]:
w = -np.sort(-arr)
w

array([0.79707351, 0.57040935, 0.57034945, 0.17746187])

In [165]:
arr2d = np.random.randn(2,4)
arr2d

array([[ 0.46708127,  1.15769478, -2.20965287,  0.55916935],
       [-0.44340202,  0.04433145,  1.63091416,  0.55933535]])

In [166]:
arr2d.ndim

2

In [167]:
row_srt = np.sort(arr2d,axis=0)
row_srt

array([[-0.44340202,  0.04433145, -2.20965287,  0.55916935],
       [ 0.46708127,  1.15769478,  1.63091416,  0.55933535]])

In [168]:
row_str = np.sort(arr2d,axis=1)
row_srt

array([[-0.44340202,  0.04433145, -2.20965287,  0.55916935],
       [ 0.46708127,  1.15769478,  1.63091416,  0.55933535]])

In [169]:
names = np.array(['Sarvar','Behruz','Alisher','Sarvar','Alisher','Akbar'])
ints = np.array([3,3,3,2,2,1,1,4,4])

In [172]:
np.unique(names)

array(['Akbar', 'Alisher', 'Behruz', 'Sarvar'], dtype='<U7')

In [175]:
set(names)

{np.str_('Akbar'), np.str_('Alisher'), np.str_('Behruz'), np.str_('Sarvar')}

In [177]:
arr1 = np.array([6,0,0,3,2,5,6])
arr2 = np.array([0,2,3])

In [178]:
np.in1d(arr1,arr2)

C:\Users\behru\AppData\Local\Temp\ipykernel_2172\1028247244.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1,arr2)


array([False,  True,  True,  True,  True, False, False])

In [179]:
arr1 = np.array([6,0,0,3,2,5,6])
arr2 = np.array([0,2,3])

In [181]:
w = np.in1d(arr1,arr2)
w

C:\Users\behru\AppData\Local\Temp\ipykernel_2172\1553706274.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  w = np.in1d(arr1,arr2)


array([False,  True,  True,  True,  True, False, False])

In [182]:
#data
names1 = np.array(['Jasur', 'Abdurahmon', 'Hasan',  'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])

In [184]:
np.setdiff1d(names1,names2)

array(['Jasur', 'Muhammad'], dtype='<U10')

In [185]:
np.setdiff1d(names2,names1)

array([], dtype='<U10')

In [187]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
np.save('data',arr)

In [190]:
w = np.load('data.npy')
w

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [193]:
w2 = np.savez('arrays',a=arr,b=arr2)
w2

In [194]:
w1 = np.load('arrays.npz')

In [195]:
w1['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
w1['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.savez_compressed('array_comp.npz',a=arr,b=arr2)

In [201]:
arrays = np.load('array_comp.npz')

In [202]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [205]:
import numpy as np

In [207]:
x = np.array([[5.,5.,5.],[4.,5.,6.]])
x

array([[5., 5., 5.],
       [4., 5., 6.]])

In [209]:
y = np.array([[1.,2.,3.],[4.,5.,6.]])
y

array([[1., 2., 3.],
       [4., 5., 6.]])

In [210]:
x+y

array([[ 6.,  7.,  8.],
       [ 8., 10., 12.]])

In [211]:
x-y

array([[4., 3., 2.],
       [0., 0., 0.]])

In [212]:
x*5

array([[25., 25., 25.],
       [20., 25., 30.]])

In [213]:
x

array([[5., 5., 5.],
       [4., 5., 6.]])

In [217]:
x = np.array([[1.,2.,3.],[4.,5.,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [218]:
y = np.array([[6.,23],[-1,7],[8,9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [219]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [220]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [221]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [ ]:
from numpy.linalg import inv

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])

c = a + b
c = c * a
print(c[2])

21


In [4]:
a = np.array([[1,2],[3,4]])
print(a.itemsize)

8


In [12]:
a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)
print(a)
print(b)

[1 2 3 4 5]
[0 2 4 6 8]


In [13]:
c = a + b
c

array([ 1,  4,  7, 10, 13])

In [14]:
print(c[4])

13


In [15]:
a.ndim

1