

## Ma'lumotlar tahlili. Numpy kutubxonasi.

# **1-AMALIY VAZIFA**

## N-o'lchamli massivlar yaratish

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish

**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning.

**Funksiya yaratilishi haqida darslik:** [bog'lanma](https://www.youtube.com/watch?v=_aDyBPYAeyU&list=PLwsopmzfbOn9Lw5D7a26THpBDgAma1Sus&index=22)


In [4]:
# JAVOBNI SHU YERGA YOZING
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  result = np.arange(n)

  return result

print(one_dim(8))

[0 1 2 3 4 5 6 7]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [5]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array

__

### Masala(2) 2-o'lchamli massivlar yaratish

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.


In [9]:
# JAVOBNI SHU YERGA YOZING
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    result = np.zeros(shape=(r,c))
    return result

print(two_dim(2,5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Yuqoridagi yozgan funksiyangizni tekshirish uchun, quyidagi cellni yuriting.

In [10]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array